### ISSUE TITLE
(Suspected) Race condition in dataset loading and error in error handler

### ISSUE THREAD

**Issue by K0shachiyamyatA** [tn3w/flask-Humanify#19]
So my friend tried to ZAP my waitress server running on 12 threats, when running user agent spoofer the race condition corrupted datasets and brought down the whole site. We tested and this doesn't happen on a single threat.
```
2025-08-30 00:43:35,032 Error getting captcha images: Expecting ':' delimiter: line 1 column 12 (char 11)
2025-08-30 00:43:35,033 Exception on /humanify/challenge [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 176, in challenge
    return self._render_challenge()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 458, in _render_challenge
    return self._render_image_challenge(return_url, error)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 480, in _render_image_challenge
    abort(500, "Could not load captcha images")
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\helpers.py", line 291, in abort
    current_app.aborter(code, *args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\werkzeug\exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Could not load captcha images

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 802, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 777, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\features\error_handler.py", line 195, in handle_error
    if code.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
2025-08-30 00:43:35,034 Error getting captcha images: 'utf-8' codec can't decode byte 0xde in position 33: invalid continuation byte
2025-08-30 00:43:35,036 Exception while serving /humanify/challenge
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 176, in challenge
    return self._render_challenge()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 458, in _render_challenge
    return self._render_image_challenge(return_url, error)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask_humanify\humanify.py", line 480, in _render_image_challenge
    abort(500, "Could not load captcha images")
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\helpers.py", line 291, in abort
    current_app.aborter(code, *args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\werkzeug\exceptions.py", line 876, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Could not load captcha images
```

**Comment by K0shachiyamyatA** [comment]
it crashes again but with a different traceback: 
```
2025-08-30 14:06:37,288 Exception on /238054310139757106 [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\humanify.py", line 305, in before_request
    limit_response = self._check_attempt_limit()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\humanify.py", line 459, in _check_attempt_limit
    if self.memory_client.is_attempt_limit_reached(ip_hash):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 576, in is_attempt_limit_reached
    return self._send_recv(f"CHECK_LIMIT:{ip_hash}") == "true"
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 555, in _send_recv
    return self.socket.recv(4096).decode("utf-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte
2025-08-30 14:06:37,290 Response status: 500 INTERNAL SERVER ERROR
2025-08-30 14:06:37,373 Exception on /humanify/1216998579391474521 [GET]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\humanify.py", line 305, in before_request
    limit_response = self._check_attempt_limit()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\humanify.py", line 459, in _check_attempt_limit
    if self.memory_client.is_attempt_limit_reached(ip_hash):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 576, in is_attempt_limit_reached
    return self._send_recv(f"CHECK_LIMIT:{ip_hash}") == "true"
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 555, in _send_recv
    return self.socket.recv(4096).decode("utf-8").strip()
``` @tn3w

**Comment by K0shachiyamyatA** [comment]
also my frp proxy doesn't return origin IP, so everyone are 127.0.0.1, after the zap humanify banned this ip, effectively banning everyone from the site, can there be a setting done to not blacklist localhost IPs? @tn3w Also it didn't ban 127.0.0.1 in previous version.

**Comment by tn3w** [comment]
This project utilizes IP addresses to manage rate limits and track failed attempts. Alternative methods, such as browser fingerprinting or using an ID cookie, are ineffective because the CAPTCHA pages do not require JavaScript to function. Users could easily remove the cookie and attempt to guess the correct CAPTCHA solution. 

I could implement cookie-based user IDs that would be used instead of IP addresses when enabled. However, this approach is not secure for the 'one-click' CAPTCHA, as there are only six possible solutions.

Regarding the issue with the `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte`, this suggests that the client is receiving responses intended for CAPTCHA image/audio requests (which contain binary data) while expecting simple text responses for CHECK_LIMIT commands. These commands are designed to limit failed attempts, preventing users from simply guessing the correct CAPTCHA image.

I have implemented a fix for this issue in commit [53053cc](https://github.com/tn3w/flask-Humanify/commit/53053cc2490c0ba0ff82f17cdae2cf5cb5bf81be).

It would be great if you could test the latest version `0.2.5` by running the following command:

```bash
pip install flask-Humanify==0.2.5
```

Thank you!

**Comment by K0shachiyamyatA** [comment]
@tn3w no more errors but does it blacklist 127.0.0.1 permanently?

**Comment by tn3w** [comment]
It only blacklists `127.0.0.1` for an hour after a local client with the same IP address fails two CAPTCHA attempts. This means that all clients using `127.0.0.1` as their IP address will be affected. The rate limiting operates in the same manner. I am currently working on an option to implement a client identifier cookie for this purpose.

**Comment by tn3w** [comment]
I have implemented the client ID cookie.

Now, when you add the option `use_client_id=True` to the **Humanify** class, or if you are only using the **RateLimiter** class, it will utilize a browser-side cookie ID value that is signed using HMAC. 

Here’s an example of how to use it:

```python
from flask import Flask
from flask_humanify import Humanify, RateLimiter

app = Flask(__name__)
humanify = Humanify(app, use_client_id=True)
humanify.register_middleware()
rate_limiter = RateLimiter(app)
...
```

Alternatively, if you are only using the **RateLimiter** class, you can implement it like this:

```python
from flask import Flask
from flask_humanify import RateLimiter

app = Flask(__name__)
rate_limiter = RateLimiter(app, use_client_id=True)
...
```

I have implemented a fix for this issue in commit [534e24f](https://github.com/tn3w/flask-Humanify/commit/534e24f26d45c774ae7a66f9eab4f25c35261036).

I would appreciate it if you could test the latest version, **0.2.6**, by executing the following command:

```bash
pip install flask-Humanify==0.2.6
```

Thank you!

**Comment by K0shachiyamyatA** [comment]
i see thanks for explaining

**Comment by tn3w** [comment]
I have resolved the issue with multiple IP addresses being contained within a single string in commit [4bed67e](https://github.com/tn3w/flask-Humanify/commit/4bed67e851a3200e6fa33b2363968bf52c99efcd).

I would appreciate it if you could verify that the problem is fixed in the latest version, **0.2.6.1**, by updating to it with the following command:

```bash
pip install flask-Humanify==0.2.6.1
```

Thank you!

**Comment by K0shachiyamyatA** [comment]
btw am i doing something wrong? It still doesn't request captcha for everyone
```
humanify = Humanify(app, challenge_type="one_click", image_dataset="animals")
humanify.register_middleware(action="challenge", url_patterns=["*"])
```
i also tried `url_patterns="*"` it didn't change anything

**Comment by tn3w** [comment]
> ```
> File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 389, in _handle_client
> response = json.dumps(self.find_groups(data[6:]))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 248, in find_groups
>     ip_obj = IPAddress(ip)
> raise AddrFormatError('failed to detect a valid IP ' 'address from %r' % addr)
> netaddr.core.AddrFormatError: failed to detect a valid IP address from 'IPV4REPLACED\nIPSET:IPV4REPLACED\nIPSET:IPV4REPLACED\nIPSET:IPV4REPLACED'
> ```
> 
> logs got fragmented due to logs from other threads but the issue persists [@tn3w](https://github.com/tn3w)

Could you check wether the printed ip address using the following code is a valid ipv4 or ipv6 address:
```
from flask import Flask
from flask_humanify import Humanify

app = Flask(__name__)
humanify = Humanify(app)
humanify.register_middleware(action="none")


@app.route("/")
def index():
    """
    Protect against bots and DDoS attacks.
    """
    print(humanify.client_ip)
    return "Hello, Human!"


if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by tn3w** [comment]
> btw am i doing something wrong? It still doesn't request captcha for everyone
> 
> ```
> humanify = Humanify(app, challenge_type="one_click", image_dataset="animals")
> humanify.register_middleware(action="challenge", url_patterns=["*"])
> ```
> 
> i also tried `url_patterns="*"` it didn't change anything

The correct way to implement this is by setting the action to **'always_challenge'**:

```python
from flask import Flask
from flask_humanify import Humanify

app = Flask(__name__)
humanify = Humanify(app)
humanify.register_middleware(action="always_challenge")
...
```

I initially thought you were referring to its functionality not working on every route URL, but you might have actually meant that it should apply to every individual client.

**Comment by tn3w** [comment]
I have fixed a typo if you have `0.2.7` installed you have to use `allways_challenge`, in version `0.2.7.1` its now `always_challenge`.

**Comment by tn3w** [comment]
> ```
> File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 389, in _handle_client
> response = json.dumps(self.find_groups(data[6:]))
>   File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_humanify\memory_server.py", line 248, in find_groups
>     ip_obj = IPAddress(ip)
> raise AddrFormatError('failed to detect a valid IP ' 'address from %r' % addr)
> netaddr.core.AddrFormatError: failed to detect a valid IP address from 'IPV4REPLACED\nIPSET:IPV4REPLACED\nIPSET:IPV4REPLACED\nIPSET:IPV4REPLACED'
> ```
> 
> logs got fragmented due to logs from other threads but the issue persists [@tn3w](https://github.com/tn3w)

I have also implemented crawler detection and added sanitization to the memory client for newlines and space characters. This may resolve the issue, as noted in commit **[ba12d58](https://github.com/tn3w/flask-Humanify/commit/ba12d5886d9f74308bc34b7fde83746829b4f515)**.

**Comment by K0shachiyamyatA** [comment]
@tn3w no errors now but each and every image request takes several seconds to complete now, even if it's 304

**Comment by K0shachiyamyatA** [comment]
i could just roll back to .5 and use a single thread and be done with it? If the problem is too deep and only gets deeper, that is.

**Comment by tn3w** [comment]
Could you please delete your **ipset.json** file? I do not fully understand the issues, as they indicate a parsing problem with the file. However, after reviewing the latest **ipset.json** file, I found that the formatting is completely correct.

**Comment by K0shachiyamyatA** [comment]
ok let me see

**Comment by tn3w** [comment]
> [@tn3w](https://github.com/tn3w) no errors now but each and every image request takes several seconds to complete now, even if it's 304

When testing with **uvicorn** on **32 workers** and using **Insomnia**, I found that the captcha page load time for grid captchas is about **50 ms**, while redirects take no more than **5 ms**. Rate limits load in approximately **8 ms**, and access denied pages appear after about **3 ms**. (Average after 100 requests) Over ngrok it only adds about **200 ms** network delay.

**Comment by K0shachiyamyatA** [comment]
> > [@tn3w](https://github.com/tn3w) no errors now but each and every image request takes several seconds to complete now, even if it's 304
> 
> When testing with **uvicorn** on **32 workers** and using **Insomnia**, I found that the captcha page load time for grid captchas is about **50 ms**, while redirects take no more than **5 ms**. Rate limits load in approximately **8 ms**, and access denied pages appear after about **3 ms**. (Average after 100 requests) Over ngrok it only adds about **200 ms** network delay.

i meant images on my own site, when using >1 thread they load super slowly and i checked dev tools there are 0 redirects

**Comment by K0shachiyamyatA** [comment]
P.S. rolled back to 5 because Ip errors don't seem to affect the site's function and threads work too

**Comment by K0shachiyamyatA** [comment]
close the issue if you want to @tn3w

**Comment by K0shachiyamyatA** [comment]
It's nothing related to the lib, it's just that my python installation got corrupted when i tried to clean re-install humanify, so i had fun 6 hours repairing it. I start the server on waitress, windows 11 23h2 enterprise machine.

**Comment by K0shachiyamyatA** [comment]
No, i use a single file and just use waitress to start the server instead of flask

**Comment by tn3w** [comment]
I cannot reproduce this issue using **Waitress** with **32 threads** behind **Nginx**, as well as with **ngrok** or **Cloudflared**. I also tested the same setup with **uvicorn**, and everything works as expected. 

The problem may be related to Windows, as some Python packages can behave differently on that platform (possibly due to socket or signal issues). To address this, I will add Linux-supported file locks using **fcntl** and implement more input validation in the memory client. It’s also possible that my setup differs from yours.

**app.py:**
```python
import logging
from flask import Flask, request
from flask_humanify import Humanify, RateLimiter, ErrorHandler
from waitress import serve

logging.basicConfig(
    filename='test.log',
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

logger = logging.getLogger(__name__)


app = Flask(__name__)
humanify = Humanify(app)
humanify.register_middleware()
rate_limiter = RateLimiter(app)
error_handler = ErrorHandler(app)


@app.route("/")
def index():
    """
    Protect against bots and DDoS attacks.
    """
    return "Hello, Human!"


if __name__ == "__main__":
    logger.info("Starting server with Waitress...")
    serve(app, host='0.0.0.0', port=8080, threads=32)
```

**Comment by tn3w** [comment]
I added per-route limit control to version **0.2.8.1**:
```python
# Using decorator syntax
@app.route("/api/data")
@rate_limiter.limit("5/minute")  # Limit specific route
def get_data():
    return "data"

# Using pattern matching
rate_limiter.set_route_limit("/api/*", "100/hour")      # All API routes
rate_limiter.set_route_limit("/admin/<id>", "5/minute") # Admin routes

# Exempt routes from rate limiting
@app.route("/health")
@rate_limiter.exempt
def health_check():
    return "OK"
```

**Comment by K0shachiyamyatA** [comment]
@tn3w i think /rate_limited page got rate limited too xddddd

**Comment by K0shachiyamyatA** [comment]
@tn3w also my users say the one_click captcha is too hard, and banning after two incorrect guesses also is too harsh

**Comment by tn3w** [comment]
The issue is that if there are more than two incorrect answers, a robot has a **1/2 chance** of guessing correctly when presented with three incorrect answers. To address this, I will implement a hardness setting to adjust the distortion of the CAPTCHA. Additionally, I will introduce a **Proof of Work (POW)** CAPTCHA, which requires JavaScript to be efficient and easy to implement. 

I will also integrate third-party CAPTCHAs, such as **Google reCAPTCHA**. Furthermore, I will add a variable to set the retry rate; however, if this is increased beyond **2**, the one-click CAPTCHA may no longer be a suitable option, and the **grid CAPTCHA** should be considered instead.

**Comment by K0shachiyamyatA** [comment]
thanks, i'll try and balance the new settings
